name: Build Plugin

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: |
          mkdir -p build/server-metrics
          rsync -av --exclude='.git' --exclude='.github' --exclude='build' --exclude='.gitignore' ./ build/server-metrics/
          cd build
          zip -r server-metrics.zip server-metrics

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: build/server-metrics.zip